---

- hosts: all
  become: yes
  tasks:
    - name: Set hostnames
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Create a sysop user
      user:
        name: sysop
        password: "{{ 'ok' | password_hash('sha512') }}"
        groups:
          - sudo
        state: present
        shell: /bin/bash  # Default: /bin/bash
        createhome: yes   # Default: yes
        home: /home/sysop # Default: /home/$name

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install a package
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - mariadb-server
        - mariadb-common
        - mariadb-client

    - name: Enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Install apache
      apt:
        name: apache2
        state: latest

    - name: Enable apache
      service:
        name: apache2
        state: started
        enabled: yes