# Webserver specific tasks

- name: Install apache
  apt:
    name: apache2
    state: latest

- name: Enable apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Install php
  apt:
    name: ["php","libapache2-mod-php","php7.4-mysql","php7.4-common","php7.4-mysql","php7.4-xml","php7.4-xmlrpc","php7.4-curl","php7.4-gd","php7.4-imagick","php7.4-cli","php7.4-dev","php7.4-imap","php7.4-mbstring","php7.4-opcache","php7.4-soap","php7.4-zip","php7.4-intl"]
    state: latest

