# Webserver specific tasks

- name: Install apache
  apt:
    name: apache2
    state: latest

- name: Enable apache
  service:
    name: apache2
    state: started
    enabled: yes

- name: Install php
  apt:
    name: ["php","libapache2-mod-php","php7.2-mysql","php7.2-common","php7.2-mysql","php7.2-xml","php7.2-xmlrpc","php7.2-curl","php7.2-gd","php7.2-imagick","php7.2-cli","php7.2-dev","php7.2-imap","php7.2-mbstring","php7.2-opcache","php7.2-soap","php7.2-zip","php7.2-intl"]
    state: latest

- name: Copy apache configuration
  copy:
    src: "files/apache.conf"
    dest: "/etc/apache2/sites-available/wordpress.conf"

- name: Enable rewrite
  shell: /usr/sbin/a2enmod rewrite

- name: Disable default site
  shell: /usr/sbin/a2dissite 000-default.conf

- name: Enable wp site
  shell: /usr/sbin/a2ensite wordpress.conf

# Actually install Wordpress
- name: Dowload wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/html"
    remote_src: yes
    creates: "/var/www/html/wordpress"

- name: Set up wp-config
  copy:
    src: "files/info.php"
    dest: "/var/www/html/wordpress/wp-config.php"

- name: Restart apache
  service:
    name: apache2
    state: restarted
