# DB specific configurations

- name: Install a package
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - mariadb-server
    - mariadb-common
    - mariadb-client
    - python3-pymysql

- name: Enable mariadb
  service:
    name: mariadb
    state: started
    enabled: yes


## FIXME: make it run on all runs, also first one
- name: Set root user password
  mysql_user:
   name: root
   password: "Akshi@123"
   append_privs: true
   #priv: "mydb.*:'root@localhost'"
   login_unix_socket: /run/mysqld/mysqld.sock


- name: Remove mariadb anonymous accounts
  mysql_user:
    name: ''
    state: absent
    login_user: root
    login_password: "Akshi@123"
    append_privs: true
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create DB for Wordpress
  mysql_db:
    name: "wordpress"
    state: present
    login_user: root
    login_password: "Akshi@123"
    #append_privs: true
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create DB user for WP
  mysql_user:
    name: "wp_user"
    password: "Akshi@123"
    host: "*"
    login_host: "*"
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: "Akshi@123"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: bind mysql remote address
  ini_file: dest=/etc/mysql/mariadb.conf.d/50-server.cnf
            section=mysqld
            option=bind-address
            value=0.0.0.0
- name: Restart mysql
  service:
    name: mysql
    state: restarted


